---
title: "109-calls"
output: html_document
date: "2023-09-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
```

Load meta.     
```{r}
meta<-read_csv("meta/meta-with-downsampled-path.csv")
```
Want to try with the 2017-2021 carcass samples? Or would that reduce the number of SNPs that pass filters since the coverage is so bad for those? We could also try, just for validation's sake, 2017 carcass and 2018 RST samples. What do you think?      

_1_ 2017-2021 carcass samples

```{r}
c<-meta %>% filter(Method=="CS") %>% filter(Filtered > 1e5)
c %>% group_by(Method, Year) %>% summarize(Count=n())
```

Probably too low.

Validation approach.

_2_ 2017 carcass to 2018 RST

```{r}
m1<-meta %>% filter(Method=="CS") %>% filter(Year==2017) %>% filter(Filtered > 1e5)
m2<-meta %>% filter(Method=="RST") %>% filter(Year==2018) %>% filter(Filtered > 1e5)

m3<-bind_rows(m1,m2)
m124<-write_csv(m3, file="meta/m124.csv")
write_tsv(m124 %>% select(NewPath), file="bamlists/124.bamlist")
write_tsv(m124 %>% select(SampleName), file="bamlists/124.names")
```


```{sh, eval=FALSE}
srun -t 3:00:00 -p high --mem=32G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12 $HOME/angsd/angsd -nthreads 24 \
-minInd 93 -bam bamlists/124.bamlist  -rf meta/chrom-list.txt \
-ref  ~/genomes/chinook-2/GCF_018296145.1_Otsh_v2.0_genomic.fna \
-minMaf 0.05 -minMapQ 10 -minQ 20 -GL 1 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doGeno 2 -doPost 1 -postCutoff 0.9 -doPlink 2 -out outputs/109/124-snps > outputs/109/124-snps.out 2> outputs/109/123-snps.err &
```

